repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-ast # checks Python syntax
      - id: check-json # checks JSON syntax
      - id: check-yaml # checks YAML syntax
      - id: check-toml # checks TOML syntax
      - id: end-of-file-fixer # checks there is a newline at the end of the file
      - id: trailing-whitespace # trims trailing whitespace
      - id: check-merge-conflict # checks for no merge conflict strings
      - id: check-shebang-scripts-are-executable # checks all shell scripts have executable permissions
        exclude: ".tmpl"
      - id: mixed-line-ending # normalizes line endings
      - id: no-commit-to-branch # prevents committing to main

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        files: '\.ipynb'
        exclude: ".ipynb_checkpoints"

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.2.1"
    hooks:
      - id: ruff
        name: ruff
        args: [--exclude, ml/]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        # same args as used in .github/workflows/linting.yml
        args: [
            --install-types,
            --explicit-package-bases,
            --non-interactive,
            --scripts-are-modules, # https://github.com/python/mypy/issues/1380#issuecomment-397138968
          ]
        additional_dependencies:
          [types-protobuf==4.24.0.20240129, boto3-stubs==1.34.45]
        exclude: "/build/|^ml/"
