name: Build DXT Extension

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-dxt-extension:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install DXT tool globally
      run: npm install -g @anthropic-ai/dxt

    - name: Run DXT pack command
      run: dxt pack

    - name: Upload DXT extension artifact
      uses: actions/upload-artifact@v4
      with:
        name: dxt-extension
        path: '*.dxt'
        retention-days: 90

    - name: List generated files
      run: |
        echo "Generated files:"
        ls -la *.dxt || echo "No .dxt files found"
