name: Linting
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      
      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"
      
      - name: Install dependencies
        run: uv sync --dev
      
      - name: Run pre-commit hook
        run: SKIP=no-commit-to-branch uv run pre-commit run --all-files