on:
  release:
    types: [published]

jobs:
  pypi-release:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    environment:
      name: PyPI
      url: https://pypi.org/project/aryn-mcp-server/
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"
      - name: Install dependencies
        run: uv sync
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - name: Set pyproject.toml version
        run: |
          sed -i "s/^version = .*/version = \"${VERSION}\"/" pyproject.toml
          echo "Using version: ${VERSION}"
          grep "version" pyproject.toml
      - name: Clean old build files
        run: rm -rf dist build *.egg-info
      - name: Build
        run: uv build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          packages-dir: dist
          audience: pypi
